services:
  shared_mysql:
    container_name: pfragatina-mysql
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pfr4g4t1n4
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS backoffice' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "

  shared_rabbitmq:
    container_name: pfragatina-rabbitmq
    image: 'rabbitmq:3.7-management'
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "8090:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=pfragatina
      - RABBITMQ_DEFAULT_PASS=pfr4g4t1n4

  test_server_java:
    container_name: pfragatina-purchase-center-test-server
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app:delegate
    depends_on:
      - shared_mysql
      - shared_rabbitmq
    tty: true
